### PR TITLE
Update the project for the new pelias schema and ES version.

### PR DESCRIPTION
**Pull request by Joxit**
Field data are longer used in pelias.
This causes an inability to use aggregations.
That's why I rewrote the project which does not use aggregations anymore.

### CODE REVIEW

**Comment by missinglink** [comment]
Very nice!

I'm not familiar with this repo, I added Julian as a reviewer and I'm happy to merge anything that works as expected 😃

**Comment by Joxit** [comment]
Yey, okay.
The old code is still present (should I delete them ?)
For the new pelias architecture, only the index.js is important and the data structure is the same as before :smile:.

**Comment by Joxit** [comment]
I fixed an issue on "aggregation" by source and layer.

I use the country name instead of the country code because some don't have a code.

**Comment by orangejulius** [comment]
Thanks!

**Pull request merged**
